library(statnet)
library(readr)
library(ergMargins)

# ==============================================================================
# Bipartite ERGM Analysis - Advanced Multivariate Specification
# ==============================================================================
# This script builds upon the bivariate ERGM analysis by addressing the 
# methodological limitations identified in the theoretical framework. 
# It implements a unified multivariate approach, incorporating exogenous 
# controls (country of origin) and robust endogenous structural parameters 
# (Geometrically Weighted Bipartite Degrees) to prevent model degeneracy.
# ==============================================================================

# Step 1: Data Ingestion and Preparation
# Load the exported CSVs generated by earlier Data Extraction Pipeline
edges_df <- read_csv("src/classification_master_refined.csv")
nodes_df <- read_csv("src/actor_metadata_refined.csv")

# Extract the primary key (feedback_ref) from chunk_id
edges_df$feedback_ref <- sub("_.*", "", edges_df$chunk_id)

# Filter edges to only include explicit 'SUPPORT' stances
edges_support <- subset(edges_df, stance == "SUPPORT")
bipartite_edgelist <- unique(edges_support[, c("feedback_ref", "concept_id")])

# Initialize the Bipartite Network Object (Mode 1: Actors, Mode 2: Concepts)
net <- network::network(bipartite_edgelist, directed = FALSE, bipartite = TRUE)

# Step 2: Attribute Specification (Node Level parameters)
vertex_names <- network::network.vertex.names(net)
index_match <- match(vertex_names, nodes_df$feedback_ref)

# 1. Actor Class (Theoretical focus: Institutional Isomorphism / Homophily)
actor_classes <- as.character(nodes_df$actor_class[index_match])
actor_classes[is.na(actor_classes)] <- "Concept"  # Mode 2 nodes need a placeholder
network::set.vertex.attribute(net, "actor_class", actor_classes)

# 2. Organization Size (Theoretical focus: Resource Dependence / Centrality)
# Convert categorical size string to numeric capacity scale.
# Micro=1, Small=2, Medium=3, Large=4. Mode 2 nodes default to 0.
org_size_map <- c(
    "Micro (1 to 9 employees)" = 1,
    "Small (10 to 49 employees)" = 2,
    "Medium (50 to 249 employees)" = 3,
    "Large (250 or more)" = 4
)
size_vals <- org_size_map[as.character(nodes_df$organization_size[index_match])]
size_vals[is.na(size_vals)] <- 0
network::set.vertex.attribute(net, "organization_size", size_vals)

# 3. Country (Methodological focus: Exogenous Geographic Control)
# control for 'country' to ensure that actor_class homophily isn't 
# simply a spurious correlation of geographic/national clustering.
country_vals <- as.character(nodes_df$country[index_match])
country_vals[is.na(country_vals)] <- "Concept" 
network::set.vertex.attribute(net, "country", country_vals)

# Step 3: Advanced Multivariate ERGM Specification
# ACADEMIC JUSTIFICATION FOR THIS MODEL:
# 1. Multivariate Control: Testing Hypotheses 1 & 2 together, while controlling 
#    for geographic clustering (`b1nodematch("country")`), proves that social 
#    and resource effects are genuine, not just artifacts of overlapping boundaries.
# 2. Endogenous Structural Controls (GW-Degree): Pure 4-cycles cause severe 
#    model degeneracy (as seen in earlier runs) due to dense cluster snowballing. 
#    We substitute pure cycles with `gwb1degree` (Actor degree distribution) and 
#    `gwb2degree` (Concept popularity). These variables statistically discount the 
#    weight of highly connected hubs (alpha = 0.5), stabilizing the model while 
#    still robustly measuring structural variance and echo chamber effects.

cat("\nEstimating Multivariate Bipartite ERGM...\n")
m_multivariate <- ergm(net ~ edges + 
                 b1nodematch("actor_class") +   # Hyp 1: Attribute Homophily
                 b1cov("organization_size") +   # Hyp 2: Resource Centrality
                 b1nodematch("country") +       # Exogenous Control: Geographic homophily
                 gwb1degree(0.5, fixed=TRUE) +  # Endogenous Control: Actor degree distribution (hub penalty)
                 gwb2degree(0.5, fixed=TRUE),   # Endogenous Control: Concept popularity distribution
    control = control.ergm(main.method = "Stochastic"),
    verbose = TRUE
)

# Output detailed summary statistics
summary(m_multivariate)

# Step 4: Model Diagnostics & Marginal Effects

# Evaluate the Goodness of Fit (Simulated vs Observed distributions)
# Using `gwb1degree` and `gwb2degree` should resolve the catastrophic failure
# seen previously in the pure cycle(4) minimum geodesic distance plots.
gof_diag <- gof(m_multivariate)
plot(gof_diag)

# Calculate Average Marginal Effects (AME) for the main theoretical variable
# in the context of the full multivariate specification.
ame_homophily <- ergm.AME(model = m_multivariate, var1 = "b1nodematch.actor_class")
print(ame_homophily)

# Scale AME at baseline probability to find the % probability increase
baseline_density <- network.density(net)
percentage_increase <- (ame_homophily[[1]] / baseline_density) * 100
cat("\nPercentage Increase in Tie Probability (Actor Class Homophily):", percentage_increase, "%\n")
